package com.xssh.design.theme

import androidx.compose.ui.graphics.Color

val XSshPrimary = Color(0xFF65D9F3)
val XSshOnPrimary = Color(0xFF003640)
val XSshPrimaryContainer = Color(0xFF164E5B)
val XSshOnPrimaryContainer = Color(0xFFB9EEFA)
val XSshSecondary = Color(0xFFBDC2FF)
val XSshOnSecondary = Color(0xFF252A60)
val XSshSecondaryContainer = Color(0xFF3A4078)
val XSshOnSecondaryContainer = Color(0xFFE0E1FF)
val XSshBackground = Color(0xFF080C12)
val XSshSurface = Color(0xFF0E141D)
val XSshSurfaceElev = Color(0xFF161E29)
val XSshSurfaceHigh = Color(0xFF202A37)
val XSshOnSurface = Color(0xFFE5EAF1)
val XSshOnSurfaceVariant = Color(0xFFB7C1CE)
val XSshOutline = Color(0xFF84909E)
val XSshOutlineVariant = Color(0xFF394552)
val XSshError = Color(0xFFFFB4AB)
val XSshOnError = Color(0xFF690005)
val XSshErrorContainer = Color(0xFF93000A)
val XSshSuccess = Color(0xFF6FE3B1)
val XSshWarning = Color(0xFFFFCB6B)

val XSshLightPrimary = Color(0xFF00677A)
val XSshLightOnPrimary = Color.White
val XSshLightPrimaryContainer = Color(0xFFB6EBF7)
val XSshLightOnPrimaryContainer = Color(0xFF001F26)
val XSshLightSecondary = Color(0xFF50578E)
val XSshLightOnSecondary = Color.White
val XSshLightSecondaryContainer = Color(0xFFDFE0FF)
val XSshLightOnSecondaryContainer = Color(0xFF0B1248)
val XSshLightBackground = Color(0xFFF6F8FC)
val XSshLightSurface = Color(0xFFFBFCFF)
val XSshLightSurfaceElev = Color(0xFFEDF1F6)
val XSshLightSurfaceHigh = Color(0xFFE3E8EF)
val XSshLightOnSurface = Color(0xFF171C22)
val XSshLightOnSurfaceVariant = Color(0xFF414A54)
val XSshLightOutline = Color(0xFF717B86)
val XSshLightOutlineVariant = Color(0xFFC1CAD4)
val XSshLightError = Color(0xFFBA1A1A)
val XSshLightErrorContainer = Color(0xFFFFDAD6)
